name: Test

on: [push, pull_request, workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update rust toolchain
        run: rustup update
      - uses: actions/cache@v4
        id: cargo-cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --release --verbose
      - name: E2E test
        run: |
          cargo run --release -- new MIT --width 80
          cargo run --release -- auto --width 80 -f
          cargo run --release -- search gpl -n 50
