name: Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-rcalc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update rust toolchain
        run: rustup update
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --release --verbose
      - name: E2E test
        run: cargo run -- new MIT --width 80
